"""initial4

Revision ID: 7343c5f48f99
Revises: 01b6c8ce3965
Create Date: 2021-11-01 04:32:05.270719

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7343c5f48f99'
down_revision = '01b6c8ce3965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('listing_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_images_listing_id'), 'images', ['listing_id'], unique=False)
    op.create_foreign_key(None, 'images', 'listings', ['listing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_listing_id'), table_name='images')
    op.drop_column('images', 'listing_id')
    # ### end Alembic commands ###
