"""initial4

Revision ID: 819871403219
Revises: 7343c5f48f99
Create Date: 2021-11-01 04:34:08.506090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '819871403219'
down_revision = '7343c5f48f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
