"""initial3

Revision ID: 01b6c8ce3965
Revises: 9d9a746dbfd7
Create Date: 2021-11-01 04:29:57.210756

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '01b6c8ce3965'
down_revision = '9d9a746dbfd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('size_x', sa.Float(), nullable=False))
    op.add_column('images', sa.Column('size_y', sa.Float(), nullable=False))
    op.create_index(op.f('ix_images_size_x'), 'images', ['size_x'], unique=False)
    op.create_index(op.f('ix_images_size_y'), 'images', ['size_y'], unique=False)
    op.add_column('listings', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_listings_url'), 'listings', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_url'), table_name='listings')
    op.drop_column('listings', 'url')
    op.drop_index(op.f('ix_images_size_y'), table_name='images')
    op.drop_index(op.f('ix_images_size_x'), table_name='images')
    op.drop_column('images', 'size_y')
    op.drop_column('images', 'size_x')
    # ### end Alembic commands ###
