"""Distances

Revision ID: 1a289167affe
Revises: cda240ae1ea5
Create Date: 2021-10-31 23:52:46.651398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a289167affe'
down_revision = 'cda240ae1ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
