"""images 2

Revision ID: 1038f05634e6
Revises: 52a4c736df24
Create Date: 2021-11-08 21:19:25.145728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1038f05634e6'
down_revision = '52a4c736df24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size_x', sa.Integer(), nullable=True),
    sa.Column('size_y', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.drop_index('ix_pictures_id', table_name='pictures')
    op.drop_table('pictures')
    op.add_column('listings', sa.Column('images_count', sa.Integer(), nullable=True))
    op.drop_column('listings', 'pictures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('pictures', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('listings', 'images_count')
    op.create_table('pictures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name='pictures_listing_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pictures_pkey')
    )
    op.create_index('ix_pictures_id', 'pictures', ['id'], unique=False)
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
