"""Images

Revision ID: 52a4c736df24
Revises: 30bb75675dca
Create Date: 2021-11-08 21:17:43.704391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a4c736df24'
down_revision = '30bb75675dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
