"""Improved Listings 2

Revision ID: 5eeb5b496362
Revises: 76c5c92496ea
Create Date: 2021-11-08 21:39:20.267455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eeb5b496362'
down_revision = '76c5c92496ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.add_column('image_tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('image_tags', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('images', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('listing_distances', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('listings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('listings', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('points', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('points', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'notes')
    op.drop_column('points', 'updated_at')
    op.drop_column('listings', 'notes')
    op.drop_column('listings', 'updated_at')
    op.drop_column('listing_distances', 'updated_at')
    op.drop_column('images', 'notes')
    op.drop_column('images', 'updated_at')
    op.drop_column('image_tags', 'notes')
    op.drop_column('image_tags', 'updated_at')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
