"""first tables

Revision ID: cda240ae1ea5
Revises: a531e7c78fbe
Create Date: 2021-10-31 23:47:10.313256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda240ae1ea5'
down_revision = 'a531e7c78fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
