"""Initial 6

Revision ID: 2be8e05a6a4f
Revises: 0101e666f4e9
Create Date: 2021-11-14 01:41:31.599029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2be8e05a6a4f'
down_revision = '0101e666f4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_points', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index('ix_interest_points_address', table_name='interest_points')
    op.drop_index('ix_interest_points_chain_name', table_name='interest_points')
    op.drop_index('ix_interest_points_distance', table_name='interest_points')
    op.drop_index('ix_interest_points_listing_id', table_name='interest_points')
    op.drop_index('ix_interest_points_website', table_name='interest_points')
    op.drop_index('ix_interest_points_website_domain', table_name='interest_points')
    op.create_index(op.f('ix_interest_points_is_active'), 'interest_points', ['is_active'], unique=False)
    op.drop_constraint('interest_points_listing_id_fkey', 'interest_points', type_='foreignkey')
    op.drop_column('interest_points', 'chain_name')
    op.drop_column('interest_points', 'listing_id')
    op.drop_column('interest_points', 'website')
    op.drop_column('interest_points', 'address')
    op.drop_column('interest_points', 'distance')
    op.drop_column('interest_points', 'website_domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_points', sa.Column('website_domain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('interest_points', sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interest_points', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('interest_points', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('interest_points', sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interest_points', sa.Column('chain_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('interest_points_listing_id_fkey', 'interest_points', 'listings', ['listing_id'], ['id'])
    op.drop_index(op.f('ix_interest_points_is_active'), table_name='interest_points')
    op.create_index('ix_interest_points_website_domain', 'interest_points', ['website_domain'], unique=False)
    op.create_index('ix_interest_points_website', 'interest_points', ['website'], unique=False)
    op.create_index('ix_interest_points_listing_id', 'interest_points', ['listing_id'], unique=False)
    op.create_index('ix_interest_points_distance', 'interest_points', ['distance'], unique=False)
    op.create_index('ix_interest_points_chain_name', 'interest_points', ['chain_name'], unique=False)
    op.create_index('ix_interest_points_address', 'interest_points', ['address'], unique=False)
    op.drop_column('interest_points', 'is_active')
    # ### end Alembic commands ###
