"""Initial 2

Revision ID: 4bee0e2ca37f
Revises: d63ccd5484d7
Create Date: 2021-11-14 00:29:04.234694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4bee0e2ca37f'
down_revision = 'd63ccd5484d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
