"""Initial 4

Revision ID: 6c98e82ae2b5
Revises: 8c61ffcb32e6
Create Date: 2021-11-14 00:39:11.321233

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6c98e82ae2b5'
down_revision = '8c61ffcb32e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('views', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_listings_views'), 'listings', ['views'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_views'), table_name='listings')
    op.drop_column('listings', 'views')
    # ### end Alembic commands ###
