"""Initial 3

Revision ID: 8c61ffcb32e6
Revises: 4bee0e2ca37f
Create Date: 2021-11-14 00:31:29.584714

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8c61ffcb32e6'
down_revision = '4bee0e2ca37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'source_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'source_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
