"""Initial 8

Revision ID: de84556d9e2a
Revises: a8810e4a9ace
Create Date: 2021-11-14 02:57:59.511295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'de84556d9e2a'
down_revision = 'a8810e4a9ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places_nearby', sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_places_nearby_query'), 'places_nearby', ['query'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_nearby_query'), table_name='places_nearby')
    op.alter_column('places_nearby', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('places_nearby', 'query')
    op.alter_column('interest_points', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
