"""test 1

Revision ID: 30bb75675dca
Revises: ae656d76b2f1
Create Date: 2021-11-01 00:25:15.834215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bb75675dca'
down_revision = 'ae656d76b2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
