"""Initial2

Revision ID: 3d98bc089107
Revises: d1727fa82c18
Create Date: 2021-11-08 22:47:44.361116

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3d98bc089107'
down_revision = 'd1727fa82c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
