"""Initial3

Revision ID: 56db8195479c
Revises: 3d98bc089107
Create Date: 2021-11-08 22:55:39.061680

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '56db8195479c'
down_revision = '3d98bc089107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_song_created_at'), 'song', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_created_at'), table_name='song')
    op.drop_column('song', 'created_at')
    # ### end Alembic commands ###
