"""Initial3

Revision ID: ef54e8e43cd0
Revises: 56db8195479c
Create Date: 2021-11-08 23:05:46.572135

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ef54e8e43cd0'
down_revision = '56db8195479c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_song_updated_at'), 'song', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_updated_at'), table_name='song')
    op.drop_column('song', 'updated_at')
    # ### end Alembic commands ###
